### PR TITLE
Fixes: #452 openssl-devel-engine is depreceted in Fedora, C10S.

### LINKED ISSUE #452: CentOS Stream 22 is failling in `test_run_binary_applidation
CentOS Stream 22 is failing on this test.

```
Running test test_run_binary_application (starting at 2024-09-25 10:49:01+00:00) ... 
-----------------------------------------------
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /root/sclorg/s2i-nodejs-container/test/test-binary/.git/
[master (root-commit) 9a3e18a] Sample commit
 2 files changed, 28 insertions(+)
 create mode 100644 hw.js
 create mode 100644 package.json
STEP 1/8: FROM quay.io/sclorg/nodejs-22-c10s:1
STEP 2/8: LABEL "io.openshift.s2i.build.image"="quay.io/sclorg/nodejs-22-c10s:1"       "io.openshift.s2i.build.source-location"="file:///root/sclorg/s2i-nodejs-container/test/test-binary"
--> 4440922bb18e
STEP 3/8: USER root
--> 0f2ac488947c
STEP 4/8: COPY upload/src/ /tmp/src
--> 2c6c1de322a3
STEP 5/8: RUN chown -R 1001:0 /tmp/src
--> 09ee77692625
STEP 6/8: USER 1001
--> dee7cebef4ed
STEP 7/8: RUN /usr/libexec/s2i/assemble
---> Installing application source ...
---> Installing all dependencies
npm error code 1
npm error path /opt/app-root/src/node_modules/node-rdkafka
npm error command failed
npm error command sh -c node-gyp rebuild
npm error make: Entering directory '/opt/app-root/src/node_modules/node-rdkafka/build'
npm error   ACTION deps_librdkafka_gyp_librdkafka_target_configure deps/librdkafka/config.h
npm error checking for OS or distribution... ok (centos)
npm error checking for C compiler from CC env... failed
npm error checking for gcc (by command)... ok
npm error checking for C++ compiler from CXX env... failed
npm error checking for C++ compiler (g++)... ok
npm error checking executable ld... ok
npm error checking executable nm... ok
npm error checking executable objdump... ok
npm error checking executable strip... ok
npm error checking executable libtool... failed (disable)
npm error checking executable ranlib... ok
npm error checking for pkgconfig (by command)... ok
npm error checking for install (by command)... ok
npm error checking for GNU ar... ok
npm error checking for PIC (by compile)... ok
npm error checking for GNU-compatible linker options... ok
npm error checking for GNU linker-script ld flag... ok
npm error checking for __atomic_32 (by compile)... ok
npm error checking for __atomic_64 (by compile)... ok
npm error checking for socket (by compile)... ok
npm error parsing version '0x020500ff'... ok (2.5.0)
npm error checking for librt (by pkg-config)... failed
npm error checking for librt (by compile)... ok
npm error checking for libpthread (by pkg-config)... failed
npm error checking for libpthread (by compile)... ok
npm error checking for c11threads (by pkg-config)... failed
npm error checking for c11threads (by compile)... ok
npm error checking for libdl (by pkg-config)... failed
npm error checking for libdl (by compile)... ok
npm error checking for zlib (by pkg-config)... failed
npm error checking for zlib (by compile)... failed (disable)
npm error checking for libcrypto (by pkg-config)... ok
npm error checking for libssl (by pkg-config)... ok
npm error checking for libsasl2 (by pkg-config)... failed
npm error checking for libsasl2 (by compile)... failed (disable)
npm error checking for libsasl (by pkg-config)... failed
npm error checking for libsasl (by compile)... failed (disable)
npm error checking for libzstd (by pkg-config)... failed
npm error checking for libzstd (by compile)... failed (disable)
npm error checking for libcurl (by pkg-config)... failed
npm error checking for libcurl (by compile)... failed (disable)
npm error checking for libm (by pkg-config)... failed
npm error checking for libm (by compile)... ok
npm error checking for liblz4 (by pkg-config)... failed
npm error checking for liblz4 (by compile)... failed (disable)
npm error checking for syslog (by compile)... ok
npm error checking for rapidjson (by compile)... failed (disable)
npm error checking for crc32chw (by compile)... ok
npm error checking for regex (by compile)... ok
npm error checking for rand_r (by compile)... ok
npm error checking for strndup (by compile)... ok
npm error checking for strlcpy (by compile)... ok
npm error checking for strerror_r (by compile)... ok
npm error checking for strcasestr (by compile)... ok
npm error checking for pthread_setname_gnu (by compile)... ok
npm error checking for nm (by env NM)... ok (cached)
npm error checking for python3 (by command)... ok
npm error checking for getrusage (by compile)... ok
npm error Generated Makefile.config
npm error Generated config.h
npm error
npm error Configuration summary:
npm error   prefix                   /opt/app-root/src/node_modules/node-rdkafka/build/deps
npm error   MKL_DISTRO               centos
npm error   SOLIB_EXT                .so
npm error   ARCH                     x86_64
npm error   CPU                      generic
npm error   GEN_PKG_CONFIG           y
npm error   libdir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps
npm error   MKL_APP_NAME             librdkafka
npm error   MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ lib
npm error checking for __atomic_32 (by compile)... ok
npm error checking for __atomic_64 (by compile)... ok
npm error checking for socket (by compile)... ok
npm error parsing version '0x020500ff'... ok (2.5.0)
npm error checking for librt (by pkg-config)... failed
npm error checking for librt (by compile)... ok
npm error checking for libpthread (by pkg-config)... failed
npm error checking for libpthread (by compile)... ok
npm error checking for c11threads (by pkg-config)... failed
npm error checking for c11threads (by compile)... ok
npm error checking for libdl (by pkg-config)... failed
npm error checking for libdl (by compile)... ok
npm error checking for zlib (by pkg-config)... failed
npm error checking for zlib (by compile)... failed (disable)
npm error checking for libcrypto (by pkg-config)... ok
npm error checking for libssl (by pkg-config)... ok
npm error checking for libsasl2 (by pkg-config)... failed
npm error checking for libsasl2 (by compile)... failed (disable)
npm error checking for libsasl (by pkg-config)... failed
npm error checking for libsasl (by compile)... failed (disable)
npm error checking for libzstd (by pkg-config)... failed
npm error checking for libzstd (by compile)... failed (disable)
npm error checking for libcurl (by pkg-config)... failed
npm error checking for libcurl (by compile)... failed (disable)
npm error checking for libm (by pkg-config)... failed
npm error checking for libm (by compile)... ok
npm error checking for liblz4 (by pkg-config)... failed
npm error checking for liblz4 (by compile)... failed (disable)
npm error checking for syslog (by compile)... ok
npm error checking for rapidjson (by compile)... failed (disable)
npm error checking for crc32chw (by compile)... ok
npm error checking for regex (by compile)... ok
npm error checking for rand_r (by compile)... ok
npm error checking for strndup (by compile)... ok
npm error checking for strlcpy (by compile)... ok
npm error checking for strerror_r (by compile)... ok
npm error checking for strcasestr (by compile)... ok
npm error checking for pthread_setname_gnu (by compile)... ok
npm error checking for nm (by env NM)... ok (cached)
npm error checking for python3 (by command)... ok
npm error checking for getrusage (by compile)... ok
npm error Generated Makefile.config
npm error Generated config.h
npm error
npm error Configuration summary:
npm error   prefix                   /opt/app-root/src/node_modules/node-rdkafka/build/deps
npm error   MKL_DISTRO               centos
npm error   SOLIB_EXT                .so
npm error   ARCH                     x86_64
npm error   CPU                      generic
npm error   GEN_PKG_CONFIG           y
npm error   libdir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps
npm error   MKL_APP_NAME             librdkafka
npm error   MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
npm error   LDFLAGS                  -L/opt/app-root/src/node_modules/node-rdkafka/build/deps
npm error   CC                       gcc
npm error   CXX                      g++
npm error   LD                       ld
npm error   NM                       nm
npm error   OBJDUMP                  objdump
npm error   STRIP                    strip
npm error   RANLIB                   ranlib
npm error   CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
npm error   PKG_CONFIG               pkg-config
npm error   INSTALL                  /usr/bin/install
npm error   HAS_GNU_AR               y
npm error   LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
npm error   LDFLAG_LINKERSCRIPT      -Wl,--version-script=
npm error   RDKAFKA_VERSION_STR      2.5.0
npm error   MKL_APP_VERSION          2.5.0
npm error   LIBS                     -lm -lssl -lcrypto -ldl -lpthread -lrt -lpthread -lrt
npm error   MKL_PKGCONFIG_LIBS_PRIVATE -lm -ldl -lpthread -lrt -lpthread -lrt
npm error   MKL_PKGCONFIG_REQUIRES_PRIVATE libcrypto libssl
npm error   CFLAGS                   
npm error   MKL_PKGCONFIG_REQUIRES   libcrypto libssl
npm error   CXXFLAGS                 -Wno-non-virtual-dtor
npm error   SYMDUMPER                $(NM) -D
npm error   MKL_DYNAMIC_LIBS         -lm -lssl -lcrypto -ldl -lpthread -lrt -lpthread -lrt
npm error   exec_prefix              /opt/app-root/src/node_modules/node-rdkafka/build/deps
npm error   bindir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps/bin
npm error   sbindir                  /opt/app-root/src/node_modules/node-rdkafka/build/deps/sbin
npm error   libexecdir               /opt/app-root/src/node_modules/node-rdkafka/build/deps/libexec
npm error   datadir                  /opt/app-root/src/node_modules/node-rdkafka/build/deps/share
npm error   sysconfdir               /opt/app-root/src/node_modules/node-rdkafka/build/deps/etc
npm error   sharedstatedir           /opt/app-root/src/node_modules/node-rdkafka/build/deps/com
npm error   localstatedir            /opt/app-root/src/node_modules/node-rdkafka/build/deps/var
npm error   runstatedir              /opt/app-root/src/node_modules/node-rdkafka/build/deps/var/run
npm error   includedir               /opt/app-root/src/node_modules/node-rdkafka/build/deps/include
npm error   infodir                  /opt/app-root/src/node_modules/node-rdkafka/build/deps/info
npm error   mandir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps/man
npm error   BUILT_WITH               GCC GXX PKGCONFIG INSTALL GNULD LDS C11THREADS LIBDL PLUGINS SSL HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW
npm error Generated config.cache
npm error
npm error Now type 'make' to build
npm error   TOUCH 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
npm error   ACTION deps_librdkafka_gyp_librdkafka_target_build_dependencies 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
npm error make[1]: Entering directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka'
npm error make[2]: Entering directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka/src'
npm error gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I.  -c rdkafka.c -o rdkafka.o
npm error make[2]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka/src'
npm error make[1]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka'
npm error rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
npm error make: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/build'
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.4.1 | linux | x64
npm error gyp info find Python using Python version 3.12.5 found at "/usr/bin/python3"
npm error gyp http GET https://nodejs.org/download/release/v22.4.1/node-v22.4.1-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v22.4.1/node-v22.4.1-headers.tar.gz
npm error gyp http GET https://nodejs.org/download/release/v22.4.1/SHASUMS256.txt
npm error gyp http 200 https://nodejs.org/download/release/v22.4.1/SHASUMS256.txt
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/usr/lib/node_modules_22/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/app-root/src/node_modules/node-rdkafka/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/usr/lib/node_modules_22/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/app-root/src/.cache/node-gyp/22.4.1/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/opt/app-root/src/.cache/node-gyp/22.4.1',
npm error gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules_22/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/opt/app-root/src/.cache/node-gyp/22.4.1/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/opt/app-root/src/node_modules/node-rdkafka',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error In file included from rdkafka_int.h:116,
npm error                  from rdkafka.c:43:
npm error rdkafka_conf.h:40:10: fatal error: openssl/engine.h: No such file or directory
npm error    40 | #include <openssl/engine.h>
npm error       |          ^~~~~~~~~~~~~~~~~~
npm error compilation terminated.
npm error make[2]: *** [../mklove/Makefile.base:97: rdkafka.o] Error 1
npm error make[1]: *** [Makefile:27: libs] Error 2
npm error make: *** [deps/librdkafka.target.mk:30: 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate] Error 2
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules_22/npm/node_modules/node-gyp/lib/build.js:209:23)
npm error gyp ERR! System Linux 6.11.0-25.el10.x86_64
npm error gyp ERR! command "/usr/bin/node-22" "/usr/lib/node_modules_22/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /opt/app-root/src/node_modules/node-rdkafka
npm error gyp ERR! node -v v22.4.1
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm notice
npm notice New patch version of npm available! 10.8.1 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice
npm error A complete log of this run can be found in: /opt/app-root/src/.npm/_logs/2024-09-25T10_49_05_206Z-debug-0.log
Error: building at STEP "RUN /usr/libexec/s2i/assemble": while running runtime: exit status 1
  ERROR: Failed to to build /tmp/tmp.LZmY7f4WEe/Dockerfile.JoTH
Test for image 'quay.io/sclorg/nodejs-22-c10s:1' FAILED (exit code: 1)
Trying to pull quay.io/sclorg/nodejs-22-c10s:1-testbinary...
Error: initializing source docker://quay.io/sclorg/nodejs-22-c10s:1-testbinary: reading manifest 1-testbinary in quay.io/sclorg/nodejs-22-c10s: unauthorized: access to the requested resource is not authorized
Waiting for container start...
Waiting for container start...
Waiting for container start...
Waiting for container start...
Waiting for container start...
Waiting for container start...
```

### PR DESCRIPTION
**Pull request by phracek**
This issue fixes CentOS Stream failures for version 22.
The commit contains also references why it was deprecated.

Closes #452 


<!-- issue-commentator = {"comment-id":"2418963358"} -->





















































































































































































































































































































































































































































































































































































































































































































































































































<!-- testing-farm = {"lock":"false","comment-id":"2419005692","data":[{"id":"581f5fa8-0b49-43c1-a668-f035ea22d590","name":"RHEL9 - 18-minimal","status":"complete","outcome":"passed","runTime":995.844137,"created":"2024-11-07T11:55:29.928680","updated":"2024-11-07T11:55:29.928687","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/581f5fa8-0b49-43c1-a668-f035ea22d590\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/581f5fa8-0b49-43c1-a668-f035ea22d590/pipeline.log\">pipeline</a>"]},{"id":"cd201001-660f-496f-b1da-7d0f8c0f0687","name":"RHEL9 - 18","status":"complete","outcome":"passed","runTime":1076.733966,"created":"2024-11-07T11:55:27.250366","updated":"2024-11-07T11:55:27.250375","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/cd201001-660f-496f-b1da-7d0f8c0f0687\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/cd201001-660f-496f-b1da-7d0f8c0f0687/pipeline.log\">pipeline</a>"]},{"id":"035a3d99-2af3-4159-8015-43b36c63114d","name":"RHEL9 - 22","status":"complete","outcome":"passed","runTime":1397.769789,"created":"2024-11-07T11:58:31.436996","updated":"2024-11-07T11:58:31.437006","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/035a3d99-2af3-4159-8015-43b36c63114d\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/035a3d99-2af3-4159-8015-43b36c63114d/pipeline.log\">pipeline</a>"]},{"id":"6407568a-91f2-437e-95fc-c106cf8e287e","name":"RHEL8 - 18-minimal","status":"complete","outcome":"passed","runTime":1146.832647,"created":"2024-11-08T09:09:01.668845","updated":"2024-11-08T09:09:01.668856","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/6407568a-91f2-437e-95fc-c106cf8e287e\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/6407568a-91f2-437e-95fc-c106cf8e287e/pipeline.log\">pipeline</a>"]},{"id":"ba52ef44-f04c-4bdb-82fa-99e846313585","name":"RHEL8 - 18","status":"complete","outcome":"passed","runTime":1162.573508,"created":"2024-11-08T09:08:58.246302","updated":"2024-11-08T09:08:58.246310","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/ba52ef44-f04c-4bdb-82fa-99e846313585\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/ba52ef44-f04c-4bdb-82fa-99e846313585/pipeline.log\">pipeline</a>"]},{"id":"dfeea8d5-886c-4a01-9767-19ccbcd52993","name":"RHEL9 - 20","status":"complete","outcome":"passed","runTime":1133.021708,"created":"2024-11-07T11:55:39.853901","updated":"2024-11-07T11:55:39.853909","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/dfeea8d5-886c-4a01-9767-19ccbcd52993\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/dfeea8d5-886c-4a01-9767-19ccbcd52993/pipeline.log\">pipeline</a>"]},{"id":"575d9adb-2833-4a21-92de-a84abf090aa4","name":"CentOS Stream 10 - 22-minimal","status":"complete","outcome":"passed","runTime":792.313375,"created":"2024-11-07T11:58:33.020419","updated":"2024-11-07T11:58:33.020426","compose":"CentOS-Stream-10","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/575d9adb-2833-4a21-92de-a84abf090aa4\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/575d9adb-2833-4a21-92de-a84abf090aa4/pipeline.log\">pipeline</a>"]},{"id":"1217d9b9-a4eb-4932-b449-0b2aacf23b23","name":"RHEL8 - 20","status":"complete","outcome":"passed","runTime":1334.755381,"created":"2024-11-08T09:08:59.948555","updated":"2024-11-08T09:08:59.948569","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/1217d9b9-a4eb-4932-b449-0b2aacf23b23\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/1217d9b9-a4eb-4932-b449-0b2aacf23b23/pipeline.log\">pipeline</a>"]},{"id":"36129505-e247-4d1f-98b6-426f5269800a","name":"CentOS Stream 10 - 22","status":"complete","outcome":"passed","runTime":1080.277193,"created":"2024-11-07T11:56:18.166221","updated":"2024-11-07T11:56:18.166229","compose":"CentOS-Stream-10","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/36129505-e247-4d1f-98b6-426f5269800a\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/36129505-e247-4d1f-98b6-426f5269800a/pipeline.log\">pipeline</a>"]},{"id":"adf0d379-7318-46ee-a5da-6cb828f5d719","name":"Fedora - 22-minimal","status":"complete","outcome":"passed","runTime":754.414265,"created":"2024-11-07T12:01:41.970902","updated":"2024-11-07T12:01:41.970907","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/adf0d379-7318-46ee-a5da-6cb828f5d719\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/adf0d379-7318-46ee-a5da-6cb828f5d719/pipeline.log\">pipeline</a>"]},{"id":"4fcdffa8-ccf4-4bef-b9a5-72c881eae04a","name":"Fedora - 18-minimal","status":"complete","outcome":"passed","runTime":5815.392731,"created":"2024-11-08T09:09:00.037490","updated":"2024-11-08T09:09:00.037502","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/4fcdffa8-ccf4-4bef-b9a5-72c881eae04a\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/4fcdffa8-ccf4-4bef-b9a5-72c881eae04a/pipeline.log\">pipeline</a>"]},{"id":"beabf739-7aef-4df9-a6c2-a92a1dc7cd39","name":"RHEL9 - 22-minimal","status":"complete","outcome":"passed","runTime":1040.431745,"created":"2024-11-07T12:02:30.643606","updated":"2024-11-07T12:02:30.643614","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/beabf739-7aef-4df9-a6c2-a92a1dc7cd39\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/beabf739-7aef-4df9-a6c2-a92a1dc7cd39/pipeline.log\">pipeline</a>"]},{"id":"ca15b8f7-0fb6-467e-9ca0-ff0e4399e4d0","name":"RHEL9 - 20-minimal","status":"complete","outcome":"passed","runTime":1436.629137,"created":"2024-11-07T11:55:49.980208","updated":"2024-11-07T11:55:49.980216","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/ca15b8f7-0fb6-467e-9ca0-ff0e4399e4d0\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/ca15b8f7-0fb6-467e-9ca0-ff0e4399e4d0/pipeline.log\">pipeline</a>"]},{"id":"bc101051-4b8f-4cb5-879f-b458aa207292","name":"Fedora - 22","status":"complete","outcome":"passed","runTime":1125.152497,"created":"2024-11-07T11:56:22.121398","updated":"2024-11-07T11:56:22.121405","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/bc101051-4b8f-4cb5-879f-b458aa207292\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/bc101051-4b8f-4cb5-879f-b458aa207292/pipeline.log\">pipeline</a>"]},{"id":"0b92afbb-d947-4c28-b441-4c1073c05e05","name":"CentOS Stream 9 - 20","status":"complete","outcome":"passed","runTime":1055.324944,"created":"2024-11-07T11:55:27.740480","updated":"2024-11-07T11:55:27.740488","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/0b92afbb-d947-4c28-b441-4c1073c05e05\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/0b92afbb-d947-4c28-b441-4c1073c05e05/pipeline.log\">pipeline</a>"]},{"id":"52ffb741-9790-4871-af87-2e411fb95241","name":"RHEL8 - 20-minimal","status":"complete","outcome":"passed","runTime":1630.993581,"created":"2024-11-07T11:55:47.634843","updated":"2024-11-07T11:55:47.634850","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/52ffb741-9790-4871-af87-2e411fb95241\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/52ffb741-9790-4871-af87-2e411fb95241/pipeline.log\">pipeline</a>"]},{"id":"8e7e75a4-c8d2-465b-8fc2-01fb1636c3de","name":"Fedora - 18","status":"complete","outcome":"passed","runTime":5972.742016,"created":"2024-11-08T09:08:59.868404","updated":"2024-11-08T09:08:59.868413","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/8e7e75a4-c8d2-465b-8fc2-01fb1636c3de\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/8e7e75a4-c8d2-465b-8fc2-01fb1636c3de/pipeline.log\">pipeline</a>"]},{"id":"bbc087ab-f140-4270-bfc8-d4869a713ce1","name":"Fedora - 20","status":"complete","outcome":"passed","runTime":6132.84614,"created":"2024-11-08T09:09:01.852787","updated":"2024-11-08T09:09:01.852797","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/bbc087ab-f140-4270-bfc8-d4869a713ce1\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/bbc087ab-f140-4270-bfc8-d4869a713ce1/pipeline.log\">pipeline</a>"]},{"id":"5ff0fd8d-9a48-4c7e-b3b2-68e2583413c7","name":"CentOS Stream 9 - 20-minimal","status":"complete","outcome":"passed","runTime":1446.650197,"created":"2024-11-07T11:55:42.747828","updated":"2024-11-07T11:55:42.747835","compose":"CentOS-Stream-9","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/5ff0fd8d-9a48-4c7e-b3b2-68e2583413c7\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/5ff0fd8d-9a48-4c7e-b3b2-68e2583413c7/pipeline.log\">pipeline</a>"]},{"id":"ca88f2bd-aa45-4d4c-bc20-e3d07c7e7f87","name":"Fedora - 20-minimal","status":"complete","outcome":"passed","runTime":1469.765247,"created":"2024-11-07T11:55:45.994363","updated":"2024-11-07T11:55:45.994371","compose":"Fedora-latest","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.dev.testing-farm.io/ca88f2bd-aa45-4d4c-bc20-e3d07c7e7f87\">test</a> ","<a href=\"https://artifacts.dev.testing-farm.io/ca88f2bd-aa45-4d4c-bc20-e3d07c7e7f87/pipeline.log\">pipeline</a>"]},{"id":"e3a52a4a-1b7d-40b1-9db2-3e3f3eaf9555","name":"RHEL8 - PyTest - OpenShift 4 - 16","status":"complete","outcome":"passed","runTime":805.669959,"created":"2024-11-07T12:20:15.846136","updated":"2024-11-07T12:20:15.846147","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/e3a52a4a-1b7d-40b1-9db2-3e3f3eaf9555\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/e3a52a4a-1b7d-40b1-9db2-3e3f3eaf9555/pipeline.log\">pipeline</a>"]},{"id":"11e97a7e-2830-4404-9ab2-286c2b1ab550","name":"RHEL9 - PyTest - OpenShift 4 - 16","status":"complete","outcome":"passed","runTime":720.457372,"created":"2024-11-07T12:15:45.212703","updated":"2024-11-07T12:15:45.212710","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/11e97a7e-2830-4404-9ab2-286c2b1ab550\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/11e97a7e-2830-4404-9ab2-286c2b1ab550/pipeline.log\">pipeline</a>"]},{"id":"350c3e83-f6f8-4120-926c-f6485a3fbf84","name":"RHEL9 - PyTest - OpenShift 4 - 16-minimal","status":"complete","outcome":"passed","runTime":721.155684,"created":"2024-11-07T12:20:27.507535","updated":"2024-11-07T12:20:27.507542","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/350c3e83-f6f8-4120-926c-f6485a3fbf84\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/350c3e83-f6f8-4120-926c-f6485a3fbf84/pipeline.log\">pipeline</a>"]},{"id":"6dd6192a-02d1-4f9d-9959-b468242f614b","name":"RHEL8 - PyTest - OpenShift 4 - 16-minimal","status":"complete","outcome":"passed","runTime":735.322136,"created":"2024-11-07T12:15:44.667045","updated":"2024-11-07T12:15:44.667052","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/6dd6192a-02d1-4f9d-9959-b468242f614b\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/6dd6192a-02d1-4f9d-9959-b468242f614b/pipeline.log\">pipeline</a>"]},{"id":"9b0574c9-e66c-4a40-a2e2-1139e443da6a","name":"RHEL9 - PyTest - OpenShift 4 - 18-minimal","status":"complete","outcome":"passed","runTime":838.971283,"created":"2024-11-07T12:23:30.553377","updated":"2024-11-07T12:23:30.553385","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/9b0574c9-e66c-4a40-a2e2-1139e443da6a\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/9b0574c9-e66c-4a40-a2e2-1139e443da6a/pipeline.log\">pipeline</a>"]},{"id":"6d1d7004-5a72-463b-8054-e25aea225c44","name":"RHEL8 - PyTest - OpenShift 4 - 18-minimal","status":"complete","outcome":"passed","runTime":974.580073,"created":"2024-11-07T12:21:14.837671","updated":"2024-11-07T12:21:14.837678","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/6d1d7004-5a72-463b-8054-e25aea225c44\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/6d1d7004-5a72-463b-8054-e25aea225c44/pipeline.log\">pipeline</a>"]},{"id":"47cb8a36-fb2f-4072-ad1b-3601957b750f","name":"RHEL9 - PyTest - OpenShift 4 - 20-minimal","status":"complete","outcome":"passed","runTime":849.435294,"created":"2024-11-07T12:32:45.823672","updated":"2024-11-07T12:32:45.823680","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/47cb8a36-fb2f-4072-ad1b-3601957b750f\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/47cb8a36-fb2f-4072-ad1b-3601957b750f/pipeline.log\">pipeline</a>"]},{"id":"3400ac7a-b8cb-422e-a12d-add82f987dbd","name":"RHEL9 - PyTest - OpenShift 4 - 18","status":"complete","outcome":"error","runTime":6950.485744,"created":"2024-11-11T07:56:01.777159","updated":"2024-11-11T07:56:01.777166","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/3400ac7a-b8cb-422e-a12d-add82f987dbd\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/3400ac7a-b8cb-422e-a12d-add82f987dbd/pipeline.log\">pipeline</a>"]},{"id":"1733ff41-2c7b-4e80-a6f3-afe429384c04","name":"RHEL8 - PyTest - OpenShift 4 - 20-minimal","status":"complete","outcome":"passed","runTime":941.220648,"created":"2024-11-07T12:28:48.021371","updated":"2024-11-07T12:28:48.021378","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/1733ff41-2c7b-4e80-a6f3-afe429384c04\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/1733ff41-2c7b-4e80-a6f3-afe429384c04/pipeline.log\">pipeline</a>"]},{"id":"1a5fe719-4c6e-4028-95d6-e6daade251d9","name":"RHEL8 - PyTest - OpenShift 4 - 18","runTime":7076.501926,"created":"2024-11-11T07:56:02.075014","updated":"2024-11-11T07:56:02.075022","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"status":"complete","outcome":"error","results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/1a5fe719-4c6e-4028-95d6-e6daade251d9\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/1a5fe719-4c6e-4028-95d6-e6daade251d9/pipeline.log\">pipeline</a>"]},{"id":"21d76ccf-6570-4c4f-a98f-daf081a5f7bc","name":"RHEL9 - PyTest - OpenShift 4 - 20","status":"complete","outcome":"passed","runTime":1993.411916,"created":"2024-11-07T12:28:49.871107","updated":"2024-11-07T12:28:49.871141","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/21d76ccf-6570-4c4f-a98f-daf081a5f7bc\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/21d76ccf-6570-4c4f-a98f-daf081a5f7bc/pipeline.log\">pipeline</a>"]},{"id":"55368283-dcb0-41e7-968d-a2bc40d6a40b","name":"RHEL9 - OpenShift 4 - 18","status":"complete","outcome":"passed","runTime":1143.62862,"created":"2024-11-07T12:12:34.671685","updated":"2024-11-07T12:12:34.671694","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/55368283-dcb0-41e7-968d-a2bc40d6a40b\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/55368283-dcb0-41e7-968d-a2bc40d6a40b/pipeline.log\">pipeline</a>"]},{"id":"69358970-823d-44b1-9b9c-af37afc9a539","name":"RHEL8 - PyTest - OpenShift 4 - 20","status":"complete","outcome":"passed","runTime":2030.229637,"created":"2024-11-07T12:23:46.360438","updated":"2024-11-07T12:23:46.360445","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/69358970-823d-44b1-9b9c-af37afc9a539\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/69358970-823d-44b1-9b9c-af37afc9a539/pipeline.log\">pipeline</a>"]},{"id":"019a5eda-a099-4db4-92ff-dfb6d95c00e6","name":"RHEL9 - OpenShift 4 - 18-minimal","status":"complete","outcome":"passed","runTime":1224.746324,"created":"2024-11-07T12:13:58.004457","updated":"2024-11-07T12:13:58.004465","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/019a5eda-a099-4db4-92ff-dfb6d95c00e6\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/019a5eda-a099-4db4-92ff-dfb6d95c00e6/pipeline.log\">pipeline</a>"]},{"id":"c26b95ec-75e8-45bf-b492-96f1834aacec","name":"RHEL8 - OpenShift 4 - 18","status":"complete","outcome":"passed","runTime":1406.493337,"created":"2024-11-07T12:12:34.761089","updated":"2024-11-07T12:12:34.761096","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/c26b95ec-75e8-45bf-b492-96f1834aacec\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/c26b95ec-75e8-45bf-b492-96f1834aacec/pipeline.log\">pipeline</a>"]},{"id":"2b177d39-f5a8-4fda-8aec-e4b3102ddd94","name":"RHEL9 - OpenShift 4 - 20","status":"complete","outcome":"passed","runTime":1104.149034,"created":"2024-11-07T12:13:55.633345","updated":"2024-11-07T12:13:55.633352","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/2b177d39-f5a8-4fda-8aec-e4b3102ddd94\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/2b177d39-f5a8-4fda-8aec-e4b3102ddd94/pipeline.log\">pipeline</a>"]},{"id":"3086c220-bf47-420e-a11e-384651b979fb","name":"RHEL8 - OpenShift 4 - 18-minimal","status":"complete","outcome":"passed","runTime":1365.046149,"created":"2024-11-07T12:12:33.843678","updated":"2024-11-07T12:12:33.843685","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/3086c220-bf47-420e-a11e-384651b979fb\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/3086c220-bf47-420e-a11e-384651b979fb/pipeline.log\">pipeline</a>"]},{"id":"2942ab8c-dece-4cc8-a96f-e2428b8a5a17","name":"RHEL9 - OpenShift 4 - 20-minimal","status":"complete","outcome":"passed","runTime":1157.8801,"created":"2024-11-07T12:14:48.829922","updated":"2024-11-07T12:14:48.829930","compose":"RHEL-9.4.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/2942ab8c-dece-4cc8-a96f-e2428b8a5a17\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/2942ab8c-dece-4cc8-a96f-e2428b8a5a17/pipeline.log\">pipeline</a>"]},{"id":"56329e8e-5fc3-4577-aadc-946101796eb4","name":"RHEL8 - OpenShift 4 - 20","status":"complete","outcome":"passed","runTime":1372.846291,"created":"2024-11-07T12:14:34.908293","updated":"2024-11-07T12:14:34.908302","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/56329e8e-5fc3-4577-aadc-946101796eb4\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/56329e8e-5fc3-4577-aadc-946101796eb4/pipeline.log\">pipeline</a>"]},{"id":"1bc5826b-6035-4359-b17b-ac610115a6ad","name":"RHEL8 - OpenShift 4 - 20-minimal","status":"complete","outcome":"passed","runTime":1380.562553,"created":"2024-11-07T12:14:57.344752","updated":"2024-11-07T12:14:57.344759","compose":"RHEL-8.10.0-Nightly","arch":"x86_64","infrastructureFailure":false,"results":["<a href=\"https://artifacts.osci.redhat.com/testing-farm/1bc5826b-6035-4359-b17b-ac610115a6ad\">test</a> ","<a href=\"https://artifacts.osci.redhat.com/testing-farm/1bc5826b-6035-4359-b17b-ac610115a6ad/pipeline.log\">pipeline</a>"]}]} -->

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@pacostas Please take a look at it. It should fix it.

**Comment by phracek** [comment]
[test]

**Comment by pacostas** [comment]
The tests do not pass due to `rm: cannot remove '/tmp/tmp.xxxxxx/./tmp.xxxxxxx.cid': No such file or directory` error which seems to happen randomly and not related to the changes of this PR. I'm not quite sure how this can be resolved. It seems like rerunning the tests will pass, or do you think is something we should spend some time looking at?

**Comment by phracek** [comment]
Rebased against master

[test-all]

**Comment by phracek** [comment]
[test-all]

File: test/test-lib-nodejs.sh [hunk 1]
```diff
@@ -578,9 +578,16 @@ function test_run_hw_application() {
...
+  if [[ "${VERSION}" == "22" ]]; then
+    if [[ "${OS}" == "c10s" ]]; then
+      # This tests is suppressed for version 22
+      # openssl/engine.h is going to be deprecated and therefore till node-rdkafka is not solve we can skip it.
+      # https://src.fedoraproject.org/rpms/openssl/c/e67e9d9c40cd2cb9547e539c658e2b63f2736762
+      # https://pkgs.devel.redhat.com/cgit/rpms/openssl/tree/openssl.spec?h=rhel-10-main#n508
+      echo "openssl-devel-engine is deprecated. Test is skipped."
+      return 0
+    fi
+  fi
```
Comment (mhdawson) [inline test/test-lib-nodejs.sh:590]: I agree this makes sense. After some pestering the maintainers of librdkakfa (on which node-rdkafka depends) have agreed to make the required fix but who knows when that will actually happen - https://github.com/nhaq-confluent

**Review by mhdawson — APPROVED** [review]
LGTM
